# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"7\n\x07Produto\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x02\x12\x0f\n\x07\x65stoque\x18\x03 \x01(\x05\"!\n\x11RequisicaoProduto\x12\x0c\n\x04nome\x18\x01 \x01(\t\",\n\x0fRespostaProduto\x12\x19\n\x07produto\x18\x01 \x01(\x0b\x32\x08.Produto\"\'\n\x0fRequisicaoPreco\x12\x14\n\x0cpreco_maximo\x18\x01 \x01(\x02\".\n\x10RespostaProdutos\x12\x1a\n\x08produtos\x18\x01 \x03(\x0b\x32\x08.Produto\"@\n\x1aRequisicaoAtualizarEstoque\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x14\n\x0cnovo_estoque\x18\x02 \x01(\x05\",\n\x18RespostaAtualizarEstoque\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xd2\x01\n\x0fServicoCatalogo\x12\x35\n\rbuscarProduto\x12\x12.RequisicaoProduto\x1a\x10.RespostaProduto\x12<\n\x15listarProdutosBaratos\x12\x10.RequisicaoPreco\x1a\x11.RespostaProdutos\x12J\n\x10\x61tualizarEstoque\x12\x1b.RequisicaoAtualizarEstoque\x1a\x19.RespostaAtualizarEstoqueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUTO']._serialized_start=17
  _globals['_PRODUTO']._serialized_end=72
  _globals['_REQUISICAOPRODUTO']._serialized_start=74
  _globals['_REQUISICAOPRODUTO']._serialized_end=107
  _globals['_RESPOSTAPRODUTO']._serialized_start=109
  _globals['_RESPOSTAPRODUTO']._serialized_end=153
  _globals['_REQUISICAOPRECO']._serialized_start=155
  _globals['_REQUISICAOPRECO']._serialized_end=194
  _globals['_RESPOSTAPRODUTOS']._serialized_start=196
  _globals['_RESPOSTAPRODUTOS']._serialized_end=242
  _globals['_REQUISICAOATUALIZARESTOQUE']._serialized_start=244
  _globals['_REQUISICAOATUALIZARESTOQUE']._serialized_end=308
  _globals['_RESPOSTAATUALIZARESTOQUE']._serialized_start=310
  _globals['_RESPOSTAATUALIZARESTOQUE']._serialized_end=354
  _globals['_SERVICOCATALOGO']._serialized_start=357
  _globals['_SERVICOCATALOGO']._serialized_end=567
# @@protoc_insertion_point(module_scope)
